kind: Deployment
apiVersion: apps/v1
metadata:
  name: substrate-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: substrate-staging
  template:
    metadata:
      labels:
        app: substrate-staging
    spec:
      containers:
        - name: substrate-staging
          image: dylanverstraete/substrate-tfgrid
          imagePullPolicy: Always
          ports:
            - containerPort: 9944
      restartPolicy: Always
---
kind: Service
apiVersion: v1
metadata:
  name: substrate-staging-service
spec:
  type: ClusterIP
  selector:
    app: substrate-staging
  ports:
    - port: 86
      targetPort: 9944 # Default port for image
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - tfgrid.tri-fold.com
    secretName: tfgrid-tls
  rules:
  - host: tfgrid.tri-fold.com
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: substrate-staging-service
            port:
              number: 86