apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tfgrid
spec:
  secretName: tfgrid-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: tri-fold.com
  dnsNames:
  - tri-fold.com
  - tfgrid.tri-fold.com